name: lean_architecture
description: "A new Flutter project."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.2.1"

dependencies:
  flutter:
    sdk: flutter
  
  flutter_localizations:
    sdk: flutter
  
  google_fonts:

  lean_requester:
    path: ../lean_requester

  scripts_package:
    path: ../scripts_package
 
  cg_core_defs:
    path: ../cg_core_defs

  uuid:
  flutter_bloc: 8.1.4
  path_provider:

  # Connectivity Monitors
  connectivity_plus: ^6.0.4
  flutter_network_connectivity: ^0.0.6

  # Cache Managers
  shared_preferences: 
  get_storage: ^2.1.1

  # DI Containers 
  get_it: 
  kiwi: ^5.0.1

  # Location
  location: ^7.0.0
  geolocator: ^12.0.0
  
dev_dependencies:
  flutter_test:
    sdk: flutter

  mocktail:
  flutter_lints:
  build_runner:

flutter:
  uses-material-design: true
  assets: 
    - assets/images/
    - assets/env/
