name: lean_architecture
description: "A new Flutter project."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.2.1"

dependencies:
  flutter:
    sdk: flutter
  
  flutter_localizations:
    sdk: flutter
  
  google_fonts:

  lean_requester:
    path: ../lean_requester
 

  uuid:
  flutter_bloc: 8.1.4
  path_provider:
  get_it: 
  shared_preferences: 

dev_dependencies:
  flutter_test:
    sdk: flutter

  mocktail:
  flutter_lints:

  build_runner:

flutter:
  uses-material-design: true
