name: lean_architecture
description: "A new Flutter project."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.6.1"

dependencies:
  flutter:
    sdk: flutter
  
  flutter_localizations:
    sdk: flutter
  
  lean_requester:
    path: ../lean_requester

  cg_core_defs:
    path: ../cg_core_defs

  flutter_bloc: 8.1.4
  animated_text_kit: ^4.2.2

  # Routing system
  go_router: ^14.2.2
  auto_route: ^9.2.0

  # Connectivity Monitors
  connectivity_plus: ^6.0.4
  flutter_network_connectivity: ^0.0.6

  # Cache Managers
  shared_preferences: 
  get_storage: ^2.1.1

  # DI Containers 
  get_it: 
  kiwi: ^5.0.1

  http: ^1.2.2
  version: ^3.0.2
  
  # Location
  location: ^7.0.0
  geolocator: ^12.0.0
  path_provider: ^2.1.5
  file_picker: ^9.0.1
  

  
dev_dependencies:
  flutter_test:
    sdk: flutter

  mocktail:
  flutter_lints:
  build_runner:
  flutter_launcher_icons:
  flutter_native_splash: 2.4.1
  
flutter:
  uses-material-design: true

  assets: 
    - assets/images/
    - assets/env/
    
  # Enable generation of localized Strings from arb files.
  generate: true